name: Checks
on: [push]
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        with:
          scandir: $GITHUB_WORKSPACE
