name: Checks
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Shell linter
        uses: azohra/shell-linter@v0.6.0
      - name: Markdown linter
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .

