name: Checks
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Shell Linter
        uses: azohra/shell-linter@v0.6.0
      - name: markdown-lint
        uses: articulate/actions-markdownlint@v1.1.0
